### ISSUE TITLE
check-mailmap always fails if `log.showSignature` is enabled in `gitconfig`

### ISSUE THREAD

**Issue by Mikaela** [jumanjihouse/pre-commit-hooks#111]
```plaintext
Detect if an email address needs to be added to mailmap.......................Failed
- hook id: check-mailmap
- exit code: 1

The following email addresses are associated with more than one name:

        0723
        [expired]
        [ultimate]
        [unknown]
        eest
        eet
        match
        messages.
        minutes.
        past

The associations include:


     19      4 minutes.  Encrypted 0 messages.
    409      Encrypted 0 messages.
```

after which there will be names and emails.

To reproduce, in repository that contains signed commits,

1. Enable the check-mailmap pre-commit hook

```yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: bundler-audit
      - id: check-mailmap
```

2. `git config log.showSignature true`
3. `pre-commit run --all-files`
