### ISSUE TITLE
Potential bug: forbid-binary with git-lfs

### ISSUE THREAD

**Issue by mihaigalos** [jumanjihouse/pre-commit-hooks#113]
Upstream issue: https://github.com/pre-commit/pre-commit/issues/3028.

### Summary
Tried to add a file to git lfs and this broke the `forbid-binary` hook.

### Description

`bash`:

```bash
git lfs track "*.pdf"
git add foo.pdf && git commit -m "chore: Test LFS"
```

This now fails since the files are binary, even though they're stored as pointers:

```
Forbid binaries..........................................................Failed
- hook id: forbid-binary
- exit code: 1
```

### Additional info
```bash
pre-commit --version
pre-commit 3.3.3
```

`.pre-commit-config.yaml`:

```yaml
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: forbid-binary
```

### Proposed solution(s)

Maybe there's an easy fix around this, potentially even looking at .gitattributes?
