### ISSUE TITLE
Trailing whitespace for .j2 files

### ISSUE THREAD

**Issue by kenorb** [jumanjihouse/pre-commit-hooks#78]
I've a simple file `template.j2`:

```
/**
 * @file
 * My file
 */
```

which doesn't have any trailing whitespace, however the hook reports otherwise.

```
$  pre-commit run -a
Check for conflict markers and core.whitespace errors.......................Failed
- hook id: git-check
- exit code: 2

template.j2:1: trailing whitespace.
+/**
template.j2:2: trailing whitespace.
+ * @file
template.j2:3: trailing whitespace.
+ * My file
template.j2:4: trailing whitespace.
+ */
```

My `.pre-commit-config.yaml`:

```
---
repos:

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: git-check
```
