### ISSUE TITLE
Executable `/usr/bin/ruby2.5` not found

### ISSUE THREAD

**Issue by kenorb** [jumanjihouse/pre-commit-hooks#79]
The following error happens on GitHub Actions. I believe Ruby is installed fine.
```
Check markdown files.....................................................Failed
- hook id: markdownlint
- exit code: 1

Executable `/usr/bin/ruby2.5` not found
```

Any clues?

Config:

```
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master  # or specific git tag
    hooks:
      - id: markdownlint
```
