### ISSUE TITLE
Error running pre-commit with shellcheck

### ISSUE THREAD

**Issue by matthewlynden** [jumanjihouse/pre-commit-hooks#82]
When running `pre-commit run --all-files` on Mac OS X 10.15.7 (bash 5.1.4) with the following .pre-commit-config.yaml

> - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '2.1.4'
    hooks:
      - id: shellcheck
        exclude: codebuild-local/codebuild_build.sh

an error is thrown

`[ERROR] The hook `shellcheck` specifies `additional_dependencies` but is using language `script` which does not install an environment.  Perhaps you meant to use a specific language?`

I have attempted to add additional configuration such as 'additional_dependencies' and 'language' but can't seem to get past this one. Is there some configuration missing that I cannot determine from the documentation?

**Comment by antonlisovenko** [comment]
yes, the same. Shellcheck is installed:
```
# which shellcheck
/usr/local/bin/shellcheck

```

**Comment by tbugfinder** [comment]
I got this error message too after upgrading pre-commit from version 2.0.1 to 2.10.0.
I've reverted back and I'm fine for now.

**Comment by tbugfinder** [comment]
Might indeed not be applicable to scripts.

https://pre-commit.com/index.html#config-additional_dependencies

**Comment by neunkasulle** [comment]
Workaround until this is fixed: Overwrite the additional reps of the hook with an empty list:
```  
 - repo: https://github.com/jumanjihouse/pre-commit-hooks
   rev: 2.1.4
   hooks:
     - id: shfmt
     - id: shellcheck
       additional_dependencies: []
```
